name: CI Workflow with API Keys

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Inject secrets into environment variables
      env:
        HF_API_OPENAI: ${{ secrets.HF_API_OPENAI }}
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        echo "HF_API_OPENAI=$HF_API_OPENAI" >> .env
        echo "HF_API_TOKEN=$HF_API_TOKEN" >> .env
        echo "YOUTUBE_API_KEY=$YOUTUBE_API_KEY" >> .env

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
